resources:
  - name: playground-repo
    type: git
    icon: github
    source:
      uri: https://github.com/prycey77/pipeline-playground
      branch: main

jobs:
  - name: set-pipeline
    serial: true
    plan:
      - get: playground-repo
        trigger: true
      - set_pipeline: self
        file: playground-repo/ci/pipeline.yaml

